export default interface IAddedCustomer{
    a: string[],
      b: string[],
      c: string[],
      d: string[],
      e: string[],
      f: string[],
      g: string[],
      h: string[],
      i: string[],
      j: string[],
      k: string[],
      l: [string,Date],
      m: [string,number],
}